Booking
Grupo2-t6/Drivent-Front pull request #3
Opened 2022-10-21 20:02 UTC by brualvess

2022-10-21 20:07 UTC, NinaS23 approved these changes

2022-10-21 20:10 UTC, NinaS23 requested changes
tem um pequeno bug na parte de somar os valores

2022-10-22 13:55 UTC, geovannicarmo commented
comment

2022-10-22 13:55 UTC, NinaS23 approved these changes

2022-10-22 13:56 UTC, geovannicarmo approved these changes

2022-10-22 13:57 UTC, merged